#!/bin/bash

LANG=C; export LANG

if [ ! "$ESTDIR" ]
then
   echo "environment variable ESTDIR is unset"
   echo "set it to your local speech tools directory e.g."
   echo '   bash$ export ESTDIR=/home/awb/projects/speech_tools/'
   echo or
   echo '   csh% setenv ESTDIR /home/awb/projects/speech_tools/'
   exit 1
fi

if [ ! "$FESTVOXDIR" ]
then
   echo "environment variable FESTVOXDIR is unset"
   echo "set it to your local festvox directory e.g."
   echo '   bash$ export FESTVOXDIR=/home/awb/projects/festvox/'
   echo or
   echo '   csh% setenv FESTVOXDIR /home/awb/projects/festvox/'
   exit 1
fi

if [ "$CLUSTERGENDIR" = "" ]
then
    export CLUSTERGENDIR=$FESTVOXDIR/src/clustergen
fi
wav=../wav # path to wavefiles folder

FEATURE_DIR=/home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/female/wav # path to the folders where features are to be stored
synth_DIR=/home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/VC_scripts/wav # path to synthesized wave
FILE=$2
SPTKDIR=/usr/local/SPTK
x2x=$SPTKDIR/bin/x2x
mcep=$SPTKDIR/bin/mcep
mgc2sp=$SPTKDIR/bin/mgc2sp
frame=$SPTKDIR/bin/frame
window=$SPTKDIR/bin/window
excite=$SPTKDIR/bin/excite
mlsadf=$SPTKDIR/bin/mlsadf
dtw=$SPTKDIR/bin/dtw
delta=$SPTKDIR/bin/delta
MINMAX=$SPTKDIR/bin/minmax
PITCH=$SPTKDIR/bin/pitch
SOPR=$SPTKDIR/bin/sopr
FRAME=$SPTKDIR/bin/frame
WINDOW=$SPTKDIR/bin/window


if [ "$1" = "wav_to_ccoeffs" ]
then

   ##### Generate filters first
   #$0 generate_filters
    
#   WORLD_FEATURE_DIR=$2
   FILE=$2
   nFFTHalf=1024 
   alpha=0.58
   mc_size=59
   order=4
   order1=5
   mc_size1=60
#   mkdir -p ${WORLD_FEATURE_DIR} ccoeffs_world

   cat $FILE | while read TRAIN_FILENAME ;

   do
    echo "Processing" $TRAIN_FILENAME 

    # Get feats
    #$WORLD_DIR/analysis  $TRAIN_FILENAME.wav ${WORLD_FEATURE_DIR}/${TRAIN_FILENAME}.f0_d ${WORLD_FEATURE_DIR}/${TRAIN_FILENAME}.sp_d ${WORLD_FEATURE_DIR}/${TRAIN_FILENAME}.ap_d    
    python extract_feats.py ${wav_dir}/$TRAIN_FILENAME.wav ${FEATURE_DIR}/${TRAIN_FILENAME}.f0_ascii ${FEATURE_DIR}/${TRAIN_FILENAME}.sp_ascii ${FEATURE_DIR}/${TRAIN_FILENAME}.ap_ascii

    # Compute log f0
    cat ${FEATURE_DIR}/${TRAIN_FILENAME}.f0_ascii | $x2x +af | $SOPR -magic 0.0 -LN -MAGIC -1.0 | $x2x +fa > ${FEATURE_DIR}/${TRAIN_FILENAME}.lf0_ascii
    echo "Computed log f0" 

    # Compute MGC
    $x2x +af ${FEATURE_DIR}/${TRAIN_FILENAME}.sp_ascii | $SOPR -R -m 32768.0 | $mcep -a $alpha -m $mc_size -l $nFFTHalf -e 1.0E-8 -j 0 -f 0.0 -q 3 | $x2x +fa$mc_size1  > ${FEATURE_DIR}/${TRAIN_FILENAME}.mgc_ascii
    echo "Computed MGC "  

    # Compute band aperiodicity 
    echo "Computing bap"
    $x2x +af ${FEATURE_DIR}/${TRAIN_FILENAME}.ap_ascii | $SOPR -R -m 32768.0 | $mcep -a $alpha -m $order -l $nFFTHalf -e 1.0E-8 -j 0 -f 0.0 -q 3 |  $x2x +fa$order1 > ${FEATURE_DIR}/${TRAIN_FILENAME}.bap_ascii
    echo $TRAIN_FILENAME "Computed band aperiodicity" 


  done
fi


if [ "$1" = "ccoeffs_to_wav" ]
then

    
 #  WORLD_FEATURE_DIR=$2
 #  TEST_DIR=$3
   FILE=$2
   nFFTHalf=1024 
   alpha=0.58
   mc_size=59
   order=4
   order1=5
   mc_size1=60
#   mkdir -p ${TEST_DIR}

   cat $FILE | while read FILENAME ;

   do
    
    # F0 
#    $x2x +af ${FEATURE_DIR}/${FILENAME}.lf0 | $SOPR -magic -1.0 -EXP -MAGIC 0  | $x2x +fa > ${FEATURE_DIR}/${FILENAME}.f0_ascii
#    echo "Got back f0"

    # SP
    $x2x +af /home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/VC_scripts/postprocessed_mgc/${FILENAME}.mgc_ascii | $mgc2sp -a $alpha -g 0 -m $mc_size -l $nFFTHalf -o 2 | $SOPR -d 32768.0 -P | $x2x +fa513 > /home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/VC_scripts/postprocessed_mgc/${FILENAME}.sp_ascii || exit
    echo "Got back spectrum"

    # AP
    $x2x +af /home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/female/${FILENAME}.bap_ascii | $mgc2sp -a $alpha -g 0 -m $order -l $nFFTHalf -o 2 | $SOPR -d 32768.0 -P | $x2x +fa513  > ${synth_DIR}/${FILENAME}.ap_ascii
    echo "Got back aperiodicity"


    # Resynth 
    python synth_file.py 16000 /home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/VC_scripts/final_f0/${FILENAME}.f0_ascii /home3/srallaba/projects/siri_expts/merlin/egs/voice_conversion/s2/chinese/feats/VC_scripts/postprocessed_mgc/${FILENAME}.sp_ascii ${synth_DIR}/${FILENAME}.ap_ascii ${synth_DIR}/${FILENAME}.wav
    echo "reconstructed"
   done
fi

